# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import uni_pb2 as uni__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in uni_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UniStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/uni.v0.Uni/GetState',
                request_serializer=uni__pb2.GetStateRequest.SerializeToString,
                response_deserializer=uni__pb2.WorldState.FromString,
                _registered_method=True)
        self.SubscribeState = channel.unary_stream(
                '/uni.v0.Uni/SubscribeState',
                request_serializer=uni__pb2.SubscribeStateRequest.SerializeToString,
                response_deserializer=uni__pb2.ReadEvent.FromString,
                _registered_method=True)
        self.Control = channel.unary_unary(
                '/uni.v0.Uni/Control',
                request_serializer=uni__pb2.Command.SerializeToString,
                response_deserializer=uni__pb2.Ack.FromString,
                _registered_method=True)
        self.SetObjectParams = channel.unary_unary(
                '/uni.v0.Uni/SetObjectParams',
                request_serializer=uni__pb2.SetObjectParamsRequest.SerializeToString,
                response_deserializer=uni__pb2.Ack.FromString,
                _registered_method=True)
        self.ListObjectTypes = channel.unary_unary(
                '/uni.v0.Uni/ListObjectTypes',
                request_serializer=uni__pb2.ListObjectTypesRequest.SerializeToString,
                response_deserializer=uni__pb2.ListObjectTypesResponse.FromString,
                _registered_method=True)
        self.DescribeObjectType = channel.unary_unary(
                '/uni.v0.Uni/DescribeObjectType',
                request_serializer=uni__pb2.DescribeObjectTypeRequest.SerializeToString,
                response_deserializer=uni__pb2.ObjectTypeSpec.FromString,
                _registered_method=True)


class UniServicer:
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """Reading
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Control(self, request, context):
        """Control (the engine owns scheduling)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetObjectParams(self, request, context):
        """Controller path — applied at the object's current local time (ADR-26)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListObjectTypes(self, request, context):
        """Schema introspection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeObjectType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UniServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=uni__pb2.GetStateRequest.FromString,
                    response_serializer=uni__pb2.WorldState.SerializeToString,
            ),
            'SubscribeState': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeState,
                    request_deserializer=uni__pb2.SubscribeStateRequest.FromString,
                    response_serializer=uni__pb2.ReadEvent.SerializeToString,
            ),
            'Control': grpc.unary_unary_rpc_method_handler(
                    servicer.Control,
                    request_deserializer=uni__pb2.Command.FromString,
                    response_serializer=uni__pb2.Ack.SerializeToString,
            ),
            'SetObjectParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SetObjectParams,
                    request_deserializer=uni__pb2.SetObjectParamsRequest.FromString,
                    response_serializer=uni__pb2.Ack.SerializeToString,
            ),
            'ListObjectTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObjectTypes,
                    request_deserializer=uni__pb2.ListObjectTypesRequest.FromString,
                    response_serializer=uni__pb2.ListObjectTypesResponse.SerializeToString,
            ),
            'DescribeObjectType': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeObjectType,
                    request_deserializer=uni__pb2.DescribeObjectTypeRequest.FromString,
                    response_serializer=uni__pb2.ObjectTypeSpec.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uni.v0.Uni', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uni.v0.Uni', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Uni:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uni.v0.Uni/GetState',
            uni__pb2.GetStateRequest.SerializeToString,
            uni__pb2.WorldState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/uni.v0.Uni/SubscribeState',
            uni__pb2.SubscribeStateRequest.SerializeToString,
            uni__pb2.ReadEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uni.v0.Uni/Control',
            uni__pb2.Command.SerializeToString,
            uni__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetObjectParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uni.v0.Uni/SetObjectParams',
            uni__pb2.SetObjectParamsRequest.SerializeToString,
            uni__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListObjectTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uni.v0.Uni/ListObjectTypes',
            uni__pb2.ListObjectTypesRequest.SerializeToString,
            uni__pb2.ListObjectTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeObjectType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uni.v0.Uni/DescribeObjectType',
            uni__pb2.DescribeObjectTypeRequest.SerializeToString,
            uni__pb2.ObjectTypeSpec.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
